"""Initial migration

Revision ID: df75d379bd92
Revises: 
Create Date: 2025-03-16 16:12:13.381419

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'df75d379bd92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcription_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=True),
    sa.Column('median_response_time', sa.Float(), nullable=True),
    sa.Column('median_audio_length', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcription_stats_id'), 'transcription_stats', ['id'], unique=False)
    op.create_table('transcriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.String(), nullable=True),
    sa.Column('audio_duration', sa.Float(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcriptions_id'), 'transcriptions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcriptions_id'), table_name='transcriptions')
    op.drop_table('transcriptions')
    op.drop_index(op.f('ix_transcription_stats_id'), table_name='transcription_stats')
    op.drop_table('transcription_stats')
    # ### end Alembic commands ###
